FROM ubuntu:20.04

RUN apt-get update
RUN apt-get install -y ca-certificates cronolog cron
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get install -yq dnsutils

ARG commit=commit
ENV commit=$commit

RUN mkdir -p /app/logs /app/bin /app/resources

WORKDIR /app

COPY ./bin/op-node /app/bin/.
RUN chmod +x /app/bin/op-node

COPY ./run_opnode.sh /app/.
RUN chmod +x /app/run_opnode.sh

CMD ["/bin/bash","run_opnode.sh"]



